### ISSUE TITLE
Add to NetPyLab

### ISSUE THREAD

**Issue by rayene** [rayene/littlepiggies#1]

**Comment by mkouriat** [comment]
voila ça fait un moment que j'ai un petit problème d'installation de netpylab et à chaque fois c'est une nouvelle erreur qui me sort en faisant le setup.py install dans une fenêtre dos dewindows vista, l'erreur est la suivante :

Traceback (most recent call last):
  File "C:\Users\mkouriat\workspace\testPythonProject\src\rayene-netpylab-0946f34\setup.py", line 58, in <module>
    license='GPL',
  File "C:\Python26\lib\distutils\core.py", line 113, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Python26\lib\site-packages\setuptools\dist.py", line 260, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "C:\Python26\lib\site-packages\setuptools\dist.py", line 284, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "C:\Python26\lib\site-packages\pkg_resources.py", line 563, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "C:\Python26\lib\site-packages\pkg_resources.py", line 799, in best_match
    return self.obtain(req, installer) # try and download/install
  File "C:\Python26\lib\site-packages\pkg_resources.py", line 811, in obtain
    return installer(requirement)
  File "C:\Python26\lib\site-packages\setuptools\dist.py", line 327, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Python26\lib\site-packages\setuptools\command\easy_install.py", line 446, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Python26\lib\site-packages\setuptools\command\easy_install.py", line 476, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Python26\lib\site-packages\setuptools\command\easy_install.py", line 642, in install_eggs
    "Couldn't find a setup script in %s" % os.path.abspath(dist_filename)
distutils.errors.DistutilsError: Couldn't find a setup script in c:\users\mkouriat\appdata\local\temp\easy_install-prytyj\download

biensur je me suis bien assuré de l'installation de setuptools, je ne comprends donc pas d'où vient le problème !
merci de votre aide
